# Generated by Django 3.2.15 on 2025-01-22 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0010_alter_stt_stt_code'),
        ('users', '0041_users_digit_group_add_datafile_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_metas', to='stts.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_metas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(help_text='Reparse events this file has been associated with.', related_name='regions', through='users.RegionMeta', to='stts.Region'),
        ),
    ]
